---
title: "Install Theme"
subtitle: "A quick tutorial to get started"  
comments: false
---

::::: {.grid .step .column-page-right}

:::: {.g-col-lg-2 .g-col-12}
## Step 1 

#### Install {.fw-light}
::::

:::: {.g-col-lg-7 .g-col-12}

## From the GitHub repo, use as a template

::: {.callout-note}
You can also follow the [GitHub guide](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template#creating-a-repository-from-a-template) to install the template to your own repository.
:::

Go to [https://github.com/nhs-r-community/quarto-nhs-theme](https://github.com/nhs-r-community/quarto-nhs-theme) and at the top right of the page there should be a green button that says `Use this template > Create a new repository`.

Use the Owner drop-down menu, and select the account you want to own the repository.

Type a name for your repository, and an optional description.

Choose a repository visibility. Either `public` for open-source/open-data work or `private`. See [NHS Digital's RAP community notes](https://nhsdigital.github.io/rap-community-of-practice/implementing_RAP/how-to-publish-your-code-in-the-open/) on how and when to publish your code in the open.

If using a personal account or your organisation allows GitHub Apps, and you want to enalbe comments, select [`giscus`](https://github.com/giscus/giscus) to enable comments. **Note:** you will also need to enable `discussions` in your repo settings for [`giscus`](https://github.com/giscus/giscus) to work.

Click **Create repository from template** and we are ready to edit.


::::

:::::

::::: {.grid .step .column-page-right}

:::: {.g-col-lg-2 .g-col-12}
## Step 2

#### Configue {.fw-light}
::::

:::: {.g-col-lg-7 .g-col-12}

## Edit the `quarto.yml` file

Open the [`quarto.yml`](https://github.com/nhs-r-community/quarto-nhs-theme/blob/main/docs/_quarto.yml) file in your new repository and 
change `nhs-r-community/quarto-nhs-theme` to `{your-user-name}/{your-project-name}`.

You can also delete links to any pages you don't need here, including the top and side bar menus.

If you want to change the bootstrap icons in the top bar menu you can change the icon perameter `icon: "box-seam"` for example, with any bootstrap icon available here: [https://icons.getbootstrap.com/](https://icons.getbootstrap.com/)

::::

:::::

::::: {.grid .step .column-page-right}

:::: {.g-col-lg-2 .g-col-12}
## Step 3

#### Add Content {.fw-light}
::::

:::: {.g-col-lg-7 .g-col-12}

##  Read the contribution guide

If you want to add new pages to the docs here, please read the [`contribute.qmd`](https://nhs-r-community.github.io/quarto-nhs-theme/contribute.html) page for details.

::::

:::::

::::: {.grid .step .column-page-right}

:::: {.g-col-lg-2 .g-col-12}
## Step 4

#### Render {.fw-light}
::::

:::: {.g-col-lg-7 .g-col-12}

## First publish locally

Your new repository will not have a `gh_pages` branch to render to, so we need to run the `quarto publish gh-pages` command in the terminal at the project folder location.

See the [Quarto publishing docs](https://quarto.org/docs/publishing/github-pages.html#publish-command) for full details.

::::

:::::

::::: {.grid .step .column-page-right}

:::: {.g-col-lg-2 .g-col-12}
## Step 5

#### Publish {.fw-light}
::::

:::: {.g-col-lg-7 .g-col-12}

## Setup GitHub.io pages
On your repo page on GitHub, go to `settings > pages > source` and click `deploy from branch`. Below that change the branch from `none` to `gh_pages`. In approx 60 seconds your new website should be deployed at `https://{user-name}.github.io/{project-name}`.

When you push any changes to the `docs/` folder from now on a tool called GitHub actions will essentially automate the preceding steps, saving a lot of time clicking. See the [GitHub Actions docs](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions) for full details.

::::

:::::